import 'package:flutter/material.dart';

enum GameDesign {
  minimal,
  neon,
  cartoon,
  luxury,
  scifi,
  nature,
  retro,
  paper,
  brutalist,
  candy,
  family,
  kids,
  senior,
  sports,
  fantasy,
  farm,
  detective,
  ocean,
  chef,
  world,
}

class GameDesignStyle {
  const GameDesignStyle({
    required this.title,
    required this.background,
    required this.surface,
    required this.primary,
    required this.secondary,
    required this.text,
    required this.gradients,
    this.dark = false,
    this.sharp = false,
    this.serif = false,
  });

  final String title;
  final Color background;
  final Color surface;
  final Color primary;
  final Color secondary;
  final Color text;
  final List<List<Color>> gradients;
  final bool dark;
  final bool sharp;
  final bool serif;
}

extension GameDesignTheme on GameDesign {
  GameDesignStyle get style {
    final values = switch (this) {
      GameDesign.minimal => (
        'ZIP PUZZLE',
        0xfff7f9fc,
        0xffffffff,
        0xff1769ff,
        0xff74a5ff,
        0xff101828,
        false,
        false,
        false,
      ),
      GameDesign.neon => (
        'ZIP // NEON',
        0xff05030b,
        0xff120d20,
        0xff00e5ff,
        0xffc144ff,
        0xffffffff,
        true,
        false,
        false,
      ),
      GameDesign.cartoon => (
        'ZIP PUZZLE',
        0xfffff3c4,
        0xffffc83d,
        0xff5ec8ff,
        0xffff6c6c,
        0xff263159,
        false,
        false,
        false,
      ),
      GameDesign.luxury => (
        'ZIP PUZZLE',
        0xff071323,
        0xff0b1b2c,
        0xffd9bf7d,
        0xff927a48,
        0xfff5ead0,
        true,
        true,
        true,
      ),
      GameDesign.scifi => (
        'PATHFINDER OS',
        0xff020914,
        0xff081a29,
        0xff45dfff,
        0xff59f0ae,
        0xffd8f8ff,
        true,
        true,
        false,
      ),
      GameDesign.nature => (
        'ZIP PUZZLE',
        0xffe9efe2,
        0xfffffdf3,
        0xff54775b,
        0xffb18b55,
        0xff263c2c,
        false,
        false,
        true,
      ),
      GameDesign.retro => (
        'ZIP ARCADE',
        0xff24113f,
        0xff36185d,
        0xffffe66d,
        0xffff4fa3,
        0xffffffff,
        true,
        true,
        false,
      ),
      GameDesign.paper => (
        'ZIP NOTES',
        0xfff0e8d8,
        0xfffffcf3,
        0xff72a8a1,
        0xffdd735e,
        0xff33312d,
        false,
        true,
        true,
      ),
      GameDesign.brutalist => (
        'ZIP PUZZLE',
        0xfff2f0e9,
        0xffffe500,
        0xff111111,
        0xffe94b35,
        0xff111111,
        false,
        true,
        false,
      ),
      GameDesign.candy => (
        'ZIP DELIGHT',
        0xffffd8ec,
        0xfffff7fc,
        0xffff64aa,
        0xffa77aff,
        0xff56396f,
        false,
        false,
        false,
      ),
      GameDesign.family => (
        'FAMILY ADVENTURE',
        0xfffff4dc,
        0xffffffff,
        0xff3478f6,
        0xffffb629,
        0xff263759,
        false,
        false,
        false,
      ),
      GameDesign.kids => (
        'ZIP TOYBOX',
        0xffbfeaff,
        0xfffff3f8,
        0xffff4f87,
        0xff55c95b,
        0xff493776,
        false,
        false,
        false,
      ),
      GameDesign.senior => (
        'ZIP PUZZLE',
        0xfff4f1e9,
        0xffffffff,
        0xff175f55,
        0xffb66a1d,
        0xff202b29,
        false,
        false,
        false,
      ),
      GameDesign.sports => (
        'ZIP LEAGUE',
        0xff071a11,
        0xff102d1d,
        0xffb8f13b,
        0xffff6a2a,
        0xffffffff,
        true,
        true,
        false,
      ),
      GameDesign.fantasy => (
        'ZIP REALMS',
        0xff17122d,
        0xff2a2048,
        0xffc998ff,
        0xffffcf67,
        0xfffff3db,
        true,
        false,
        true,
      ),
      GameDesign.farm => (
        'ZIP HARVEST',
        0xffdff1c8,
        0xfffff8da,
        0xff4d793c,
        0xffd94e3d,
        0xff304126,
        false,
        false,
        false,
      ),
      GameDesign.detective => (
        'ZIP CASES',
        0xff282623,
        0xffeee7d5,
        0xff8c2424,
        0xffd0b777,
        0xff221f1b,
        true,
        true,
        true,
      ),
      GameDesign.ocean => (
        'ZIP OCEAN',
        0xff043a55,
        0xffd8ffff,
        0xff007e9e,
        0xffff8066,
        0xff06435a,
        true,
        false,
        false,
      ),
      GameDesign.chef => (
        'ZIP KITCHEN',
        0xffffe1ca,
        0xfffffbef,
        0xffd33d34,
        0xffffd16b,
        0xff4c2926,
        false,
        false,
        false,
      ),
      GameDesign.world => (
        'ZIP JOURNEY',
        0xffe6ecdd,
        0xfffffcf2,
        0xff176b74,
        0xffdf6548,
        0xff233c43,
        false,
        false,
        false,
      ),
    };
    final primary = Color(values.$4);
    final secondary = Color(values.$5);
    return GameDesignStyle(
      title: values.$1,
      background: Color(values.$2),
      surface: Color(values.$3),
      primary: primary,
      secondary: secondary,
      text: Color(values.$6),
      dark: values.$7,
      sharp: values.$8,
      serif: values.$9,
      gradients: [
        [primary, secondary, Color.lerp(primary, Colors.white, .42)!],
        [secondary, primary, Color.lerp(secondary, Colors.black, .25)!],
        [primary, Color.lerp(primary, secondary, .5)!, secondary],
        [
          Color.lerp(primary, Colors.white, .55)!,
          primary,
          Color.lerp(secondary, Colors.black, .15)!,
        ],
      ],
    );
  }
}
